### ISSUE TITLE
Unable to run node uma

### ISSUE THREAD

**Issue by utish** [atricore/node-uma#3]
When running node uma, it throws an error:
```
$ node uma
module.js:471
    throw err;
    ^

Error: Cannot find module 'c:\projects\myapp\uma'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

```
Thanks.

**Comment by gbrigandi** [comment]
Hi,
Please make sure that you have run "npm install node-uma" .
Hope this helps.
Regards.
Gianluca.

**Comment by utishrajk** [comment]
Yes, I've run "npm install node-uma". 

$ npm install node-uma
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN saveError ENOENT: no such file or directory, open 'c:\projects\myapp2\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'c:\projects\myapp2\package.json'
npm WARN myapp2 No description
npm WARN myapp2 No repository field.
npm WARN myapp2 No README data
npm WARN myapp2 No license field.

+ node-uma@1.0.1
added 5 packages in 4.668s

x.y@COMP /c/projects/myapp2
$ node uma
module.js:471
    throw err;
    ^

Error: Cannot find module 'c:\projects\myapp2\uma'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3

Any suggestions? Thanks.

**Comment by gbrigandi** [comment]
Hi,
The UMA node package doesn't ship with an example server. It's basically middleware to be plugged into Express.
The documentation was improved as this wasn't really clear. 
Regards,
Gianluca.
